java_binary(
    name = "tempserver",
    srcs = glob(["*.java"]),
#    resources = ["temperature.html"],
    deps = [
        "//third_party:guava",
    ],
    main_class = "com.dlila.tempserver.Server",
)

